### ISSUE TITLE
remote agent support

### ISSUE THREAD

**Issue by cash** [DorsetProject/dorset-framework#11]
Define a web service API that remote agents must support. Add a class to core for communicating with the remote agent that only has configuration of the base URL. This requires improving the HttpClient.

**Comment by cash** [comment]
7ac883add358e87fe21291c77fc139c3f127a45f adds the remote agent. Need to add a demo of a remote agent - probably in python and add to demos.

**Comment by cabishop** [comment]
Python demo added
