### ISSUE TITLE
Add the CommandLineClient as a framework component

### ISSUE THREAD

**Issue by davidpatrone** [DorsetProject/dorset-framework#51]
The command line client in the demo package is a useful component to throw an agent in for quick testing. It should be generalized and made a component of the framework.

**Comment by cash** [comment]
Agreed. Lets create a project named "tools" under components and add it there (or if you have a better name, please suggest).

**Comment by davidpatrone** [comment]
With that pull request merged, I'm going to call this issue closed.

**Comment by cash** [comment]
Also, you can close an issue with a commit message (or the title of a pull request) by doing something like this:

```
Fixes #52 - adds a command line client to the framework
```

Documentation: https://help.github.com/articles/closing-issues-via-commit-messages/
