### ISSUE TITLE
LDAP User Service 

### ISSUE THREAD

**Issue by cabishop** [DorsetProject/dorset-framework#59]
This includes session handling for web and creating the LDAP user service in components.

**Comment by cash** [comment]
Links that may be helpful:

http://docs.oracle.com/javase/jndi/tutorial/getStarted/overview/index.html
https://coderanch.com/t/593104/java/LDAP-Connection-practice
http://www.adamretter.org.uk/blog/entries/LDAPTest.java
https://github.com/goeh/grails-selection-ldap/blob/master/src/java/org/apache/directory/groovyldap/LDAP.java
https://github.com/kdabir/active-directory-lookup/blob/9c4adafa958beaf81a599c8deb4ea44a9f5f48ae/src/main/java/io/github/kdabir/adl/api/mapper/DefaultSearchResultMapper.java
https://github.com/admiralobvious/flask-simpleldap/blob/master/flask_simpleldap/__init__.py
